repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: go-test
        name: go-test
        entry: go-pre-commit go-test
        files: '\.go$'
        language: system
        description: Run your Go unit tests
      - id: gofumports
        name: gofumports
        entry: go-pre-commit gofumports
        files: '\.go$'
        language: system
        description: Format your Go code with gofumports
      - id: gofumpt
        name: gofumpt
        entry: go-pre-commit gofumpt
        files: '\.go$'
        language: system
        description: Format your Go code with gofumpt
      - id: golangci-lint
        name: golangci-lint
        entry: go-pre-commit golangci-lint
        files: '\.go$'
        language: system
        description: Check your Go code with golangci-lint
      - id: golint
        name: golint
        entry: go-pre-commit golint
        files: '\.go$'
        language: system
        description: Check your Go code with golint
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go-pre-commit go-mod-tidy
        files: ''
        language: system
        description: Prune no-longer required commits from go.mod
      - id: golines
        name: golines
        entry: go-pre-commit golines
        files: '\.go$'
        language: system
        description: Check your Go code with golines
